name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  REGISTRY: reg.bermos.dev
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: reg.bermos.dev
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reg.bermos.dev/dabbot:$(date +%s) --tag reg.bermos.dev/dabbot:latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: |
          $(date +%s)
          latest
