name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  REGISTRY: reg.bermos.dev
  IMAGE_NAME: dabbot

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date -u '+%y.%V.%u%H%M%S')"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy Stage
      run: curl --request POST '${{ secrets.REGISTRY_USERNAME }}'